from gui import common_clipboard as _common_clipboard
from gui import common_route_progress as _common_route_progress
from gui import common_tables as _common_tables
from gui.common_clipboard import (
    compute_route_signature,
    copy_text_to_clipboard,
    format_route_for_clipboard,
    try_copy_to_clipboard,
)
from gui.common_tables import (
    COPIED_BG,
    COPIED_FG,
    HOVER_BG,
    _align_text,
    _apply_saved_sort,
    _apply_treeview_sort,
    _attach_treeview_hover,
    _compute_column_widths,
    _ensure_route_indices,
    _escape_delimited_value,
    _format_bool,
    _format_number,
    _format_treeview_header,
    _get_default_visible_columns,
    _get_saved_sort_state,
    _get_saved_visible_columns,
    _get_treeview_row,
    _get_value_by_key,
    _get_visible_columns,
    _is_persist_sort_enabled,
    _load_column_presets,
    _open_columns_picker,
    _refresh_table_listbox,
    _refresh_table_treeview,
    _sanitize_preset_columns,
    _sanitize_visible_columns,
    _save_column_presets,
    _save_sort_state,
    _save_visible_columns,
    _set_list_header,
    _sort_key_for_value,
    _sort_treeview,
    _update_treeview_lp,
    _update_treeview_sort_indicators,
    attach_results_context_menu,
    format_row_delimited,
    format_value,
    podswietl_cel,
    render_table,
    render_table_lines,
    render_table_treeview,
    set_listbox_refresh_observer,
    stworz_liste_trasy,
    stworz_tabele_trasy,
    wypelnij_liste,
)
from gui.common_route_progress import (
    STATUS_TEXTS,
    _copy_next_hop_at_index,
    _emit_next_hop_status,
    _extract_route_systems,
    _get_active_spansh_milestone_norm,
    _get_navroute_context,
    _get_navroute_ordered_systems,
    _get_navroute_remaining_to_target,
    _is_navroute_aligned_with_active_milestone,
    _level_color,
    _maybe_emit_milestone_progress,
    _maybe_emit_milestone_progress_from_navroute,
    _maybe_toast,
    _resolve_active_milestone,
    _set_active_route_data,
    _update_active_route_list_mark,
    copy_next_hop_manual,
    emit_status,
    get_active_route_next_system,
    get_last_route_sig,
    get_last_route_systems,
    get_last_route_text,
    handle_route_ready_autoclipboard,
    normalize_system_name,
    register_active_route_list,
    set_last_route_data,
    update_next_hop_on_system,
)


def __getattr__(name: str):
    for module in (_common_route_progress, _common_tables, _common_clipboard):
        if hasattr(module, name):
            return getattr(module, name)
    raise AttributeError(f"module 'gui.common' has no attribute {name!r}")
