from __future__ import annotations

# Planner UI labels (PL-first, ASCII-safe).
LABEL_START = "Start"
LABEL_TARGET = "Cel"
LABEL_SYSTEM = "System"
LABEL_STATION = "Stacja"
LABEL_STATION_REQUIRED = "Stacja*"

LABEL_JUMP_RANGE = "Zasieg skoku [ly]"
LABEL_EFFICIENCY = "Efektywnosc [%]"
LABEL_SUPERCHARGE = "Tryb doladowania"
LABEL_VIA = "Przez"
LABEL_RADIUS = "Promien [ly]"
LABEL_MAX_SYSTEMS = "Maks. systemow [szt.]"
LABEL_MAX_DISTANCE = "Maks. dystans [ls]"
LABEL_MIN_SCAN_VALUE = "Min. wartosc skanu [cr]"
LABEL_MIN_LANDMARK_VALUE = "Min. wartosc landmarku [cr]"

LABEL_CAPITAL = "Kapital [cr]"
LABEL_MAX_HOP = "Maks. skok [ly]"
LABEL_CARGO = "Ladownosc [t]"
LABEL_MAX_HOPS = "Maks. skokow [szt.]"
LABEL_MAX_AGE = "Maks. wiek rynku [dni]"
LABEL_MARKET_AGE_CUTOFF = "Starsze niz [YYYY-MM-DD HH:MM]"
LABEL_MARKET_AGE_SLIDER = "Wiek rynku [h]"

LABEL_LOOP = "Petla"
LABEL_USE_MAP = "Uzyj mapy"
LABEL_AVOID_THARGOIDS = "Unikaj Thargoidow"

BUTTON_CALCULATE = "Wyznacz trase"
BUTTON_CALCULATE_TRADE = "Wyznacz trase handlowa"
BUTTON_CLEAR = "Wyczysc"
BUTTON_REVERSE = "Odwroc"
BUTTON_ADD = "Dodaj"
BUTTON_REMOVE = "Usun"

FLAG_LARGE_PAD = "Duze ladowisko"
FLAG_PLANETARY = "Planetarna"
FLAG_PLAYER_OWNED = "Wlasnosc gracza"
FLAG_RESTRICTED = "Ograniczony dostep"
FLAG_PROHIBITED = "Zakazany dostep"
FLAG_AVOID_LOOPS = "Unikaj petli"
FLAG_ALLOW_PERMITS = "Pozwol na pozwolenia"

DETECTED_PREFIX = "Wykryto"

LIST_TITLE_NEUTRON = "Trasa: Neutron"
LIST_TITLE_TRADE = "Trasa: Handel"
LIST_TITLE_RICHES = "Trasa: Riches"
LIST_TITLE_AMMONIA = "Trasa: Ammonia"
LIST_TITLE_ELW = "Trasa: ELW"
LIST_TITLE_HMC = "Trasa: HMC / Rocky"
LIST_TITLE_EXOMASTERY = "Trasa: Exomastery"

TAB_MAIN_PULPIT = "Pulpit"
TAB_MAIN_SPANSH = "Spansh"
TAB_MAIN_INARA = "Inara"
TAB_MAIN_EDTOOLS = "EDTools"
TAB_MAIN_ENGINEER = "Inzynier"
TAB_MAIN_JOURNAL = "Dziennik"

TAB_SPANSH_NEUTRON = "Neutron"
TAB_SPANSH_RICHES = "Riches"
TAB_SPANSH_AMMONIA = "Ammonia"
TAB_SPANSH_ELW = "Earth-like"
TAB_SPANSH_HMC = "Rocky/HMC"
TAB_SPANSH_EXO = "Exo"
TAB_SPANSH_TRADE = "Trade"
TAB_SPANSH_TOURIST = "Tourist (beta)"
TAB_SPANSH_FLEET = "Fleet Carrier (beta)"
TAB_SPANSH_COLONISATION = "Colonisation (beta)"
TAB_SPANSH_GALAXY = "Galaxy (later)"

TAB_SETTINGS_GENERAL = "Ogolne"
TAB_SETTINGS_ASSISTANTS = "Asystenci"
TAB_SETTINGS_EXPLORATION = "Eksploracja"
TAB_SETTINGS_TRADE = "Handel"
TAB_SETTINGS_ENGINEER = "Inzynier"
TAB_SETTINGS_ADVANCED = "Zaawansowane"

TABLE_HDR_DONE = "Wyk."
TABLE_HDR_SYSTEM = "System"
TABLE_HDR_SYSTEM_NAME = "System"
TABLE_HDR_BODY_NAME = "Cialo"
TABLE_HDR_NAME = "Nazwa"
TABLE_HDR_SUBTYPE = "Typ"
TABLE_HDR_TERRA = "Terra"
TABLE_HDR_DISTANCE_LY = "Dystans [ly]"
TABLE_HDR_REMAINING_LY = "Pozostalo [ly]"
TABLE_HDR_DISTANCE_LS = "Dystans [ls]"
TABLE_HDR_SCAN_VALUE = "Wartosc skanu [cr]"
TABLE_HDR_MAPPING_VALUE = "Wartosc mapy [cr]"
TABLE_HDR_JUMPS = "Skoki [szt]"
TABLE_HDR_NEUTRON = "Neutron"
TABLE_HDR_FROM = "Z"
TABLE_HDR_TO = "Do"
TABLE_HDR_FROM_STATION = "Stacja Z"
TABLE_HDR_TO_STATION = "Stacja Do"
TABLE_HDR_COMMODITY = "Towar"
TABLE_HDR_PROFIT = "Zysk [cr]"
TABLE_HDR_PROFIT_TON = "Zysk/t [cr]"

PLACEHOLDER_TITLE = "Wkrotce"
PLACEHOLDER_LINE_1 = "Ta funkcja jest w przygotowaniu."
PLACEHOLDER_LINE_2 = "Sledz roadmape lub aktualizacje Renaty."
PLACEHOLDER_ENABLED_TITLE = "Beta aktywna"
PLACEHOLDER_ENABLED_LINE_1 = "Funkcja jest wlaczona, ale jeszcze niegotowa."
PLACEHOLDER_ENABLED_LINE_2 = "To widok tymczasowy dla wersji dev."
